{
  pkgs,
  config,
  myvars,
  ...
}: {

  # Don't allow mutation of users outside the config.
  users.mutableUsers = false;

  users.groups = {
    "${myvars.username}" = {};
    docker = {};
  };

  # set user's default shell in system-wide
  users.defaultUserShell = pkgs.bashInteractive;

  users.users."${myvars.username}" = {
    # generated by `mkpasswd -m scrypt`
    # we have to use initialHashedPassword here when using tmpfs for /
    inherit (myvars) initialHashedPassword;
    home = "/home/${myvars.username}";
    isNormalUser = true;
    extraGroups = [
      myvars.username
      "users"
      "networkmanager"
      "wheel"
      "docker"
    ];
    packages = with pkgs; [];

    openssh.authorizedKeys.keys = myvars.sshAuthorizedKeys;
  };

}
