#!/usr/bin/env bash

## Autostart Programs

# Kill already running process
_ps=(waybar mako mpd)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done

# Set wallpaper via a wallpaper.service
# it will by start by home-manager automatically, do not need to restart it here.
# systemctl --user restart wallpaper.service

# Launch statusbar (waybar)
~/.config/hypr/scripts/statusbar &

# Launch notification daemon (mako)
~/.config/hypr/scripts/notifications &

# Start mpd
exec mpd &
